language: ruby
rvm:
  - 2.5.1

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system

before_script:
  - psql -c "CREATE USER \"careerfoundry-challenge\" WITH PASSWORD 'careerfoundry-challenge';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"careerfoundry-challenge_test\";" -U postgres
  - psql -c "CREATE DATABASE \"careerfoundry-challenge_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

notifications:
  email: false

cache:
  bundler: true