language: ruby
rvm:
  - 2.5.1

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

before_script:
  - psql -c "CREATE USER \"rails-bootstrap\" WITH PASSWORD 'rails-bootstrap';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"rails-bootstrap_test\";" -U postgres
  - psql -c "CREATE DATABASE \"rails-bootstrap_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple
  - bundle exec scss-lint app/assets/stylesheets/

notifications:
  email: false

cache:
  bundler: true